version: '3.9'

{% if SERVICES is not defined or SERVICES.replace('"', '').replace("'",'') == '' -%}
{% set SERVICES = [] -%}
{% else -%}
{% set SERVICES = SERVICES.split(' ') -%}
{% endif -%}

{% set s = [] -%}
{% if SERVICES -%}
services:
{% for item in SERVICES -%}
{% include item %}
{% endfor -%}
{% endif %}

networks:
  {{ BRIDGE }}:
    name: {{ BRIDGE }}
    driver: {{ DRIVER }}
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: {{ SUBNET }}
  
volumes:
  postgres:
