# COMMON
LOCALHOST = localhost
MIGRATIONS_DIR = migrations
SRV_DB = fizzbuzz
SRV_PASSWORD = 12345
SRV_USER = foobar

PROJECT_DIR = $(shell pwd)

OUT_DIR = $(PWD)/.output
TMPL_DIR = $(DEVTOOLS_DIR)/tools

DATABASE_URL = postgres://$(SRV_USER):$(SRV_PASSWORD)@$(PG_HOST):$(PG_PORT)/$(SRV_DB)

# TOOL: CARGO
CARGO_OUT_DIR = $(OUT_DIR)/cargo
CARGO_MAKE = $(CARGO_OUT_DIR)/Makefile
CARGO_ENVS += RUSTFLAGS="-C target-feature=-crt-static"
CARGO_ENVS += BUILD_VERSION=$(git describe --tags)
CARGO_ENVS += DATABASE_URL=$(DATABASE_URL)

# TOOL: POSTGRESQL
POSTGRESQL_OUT_DIR = $(OUT_DIR)/postgresql
POSTGRESQL_MAKE = $(POSTGRESQL_OUT_DIR)/Makefile

# TOOL: PG_CTL
PG_CTL_OUT_DIR = $(OUT_DIR)/pg_ctl
PG_CTL_MAKE = $(PG_CTL_OUT_DIR)/Makefile
PG_CTL_ARTEFACTS_DIR = $(PG_CTL_OUT_DIR)/.artefacts
PG_CTL_DATADIR = $(PG_CTL_OUT_DIR)/pg_data

# TOOL: PSQL
PSQL_OUT_DIR = $(OUT_DIR)/psql
PSQL_MAKE = $(PSQL_OUT_DIR)/Makefile
PSQL_ARTEFACTS_DIR = $(PSQL_OUT_DIR)/.artefacts
PSQL_USER_NAME = $(SRV_USER)
PSQL_USER_DB = $(SRV_DB)
PSQL_USER_PASSWORD = $(SRV_PASSWORD)

# TOOL: REDIS
REDIS_OUT_DIR = $(OUT_DIR)/redis
REDIS_MAKE = $(REDIS_OUT_DIR)/Makefile
REDIS_ARTEFACTS_DIR = $(REDIS_OUT_DIR)/.artefacts
REDIS_USER_NAME = $(SRV_USER)
REDIS_USER_DB = 0
REDIS_USER_PASSWORD = $(SRV_PASSWORD)

# TOOL: VENV
VENV_OUT_DIR = $(OUT_DIR)/venv
VENV_MAKE = $(VENV_OUT_DIR)/Makefile
VENV_ARTEFACTS_DIR = $(VENV_OUT_DIR)/.artefacts
VENV_VENV_DIR = $(VENV_OUT_DIR)/.venv
VENV_REQUIREMENTS = $(DEVTOOLS_DIR)/render/requirements.txt

# TOOL: PYTHON
PY_OUT_DIR = $(OUT_DIR)/python
PY_MAKE = $(PY_OUT_DIR)/Makefile
PY_ARTEFACTS_DIR = $(PY_OUT_DIR)/.artefacts
