version: '3.9'

services:
  {{ REDIS }}:
    image: {{ REDIS_IMAGE }}
    container_name: {{ REDIS }}
    networks:
      - {{ REDIS_BRIDGE }}
    command: redis-server --requirepass "{{ REDIS_ADMIN_PASSWORD }}"
    ports:
      - "{{ REDIS_PUBLISH }}"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
    restart: always
  {{ PG }}:
    image: {{ PG_IMAGE }}
    container_name: {{ PG }}
    networks:
      - {{ PG_BRIDGE }}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "{{ PG_PUBLISH }}"
    command: ["postgres", "-c", "log_statement=all"]
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
    restart: always
{%- set e = [] -%}
{% if PG_ENVS -%}
{% for item in PG_ENVS.split(' ') -%}
{% do e.append("{}={}".format(item, env[item])) -%}
{% endfor -%}
{% endif -%}
{% if e %}
    environment:
      - {{ e|join('\n      - ') }}
{% endif %}
  {{ RUST }}:
    build:
      context: {{ RUST_CTX }}
      dockerfile: {{ RUST_DOCKERFILE }}
      args:
          BASE_IMAGE: {{ RUST_BASE_IMAGE }}
          RUST_VERSION: {{ RUST_VERSION }}
          TARGET_ARCH: {{ TARGET_ARCH }}
          SQLX_VERSION: {{ SQLX_VERSION }}
    image: {{ RUST_IMAGE }}
  {{ FOO }}:
    build:
      context: {{ FOO_CTX }}
      dockerfile: {{ FOO_DOCKERFILE }}
      args:
          APP: {{ FOO }}
          BUILDER:  {{ FOO_BUILDER }}
          BASE_IMAGE:  {{ FOO_BASE_IMAGE }}
          BUILD_PROFILE: {{ FOO_BUILD_PROFILE }}
          BUILD_VERSION: {{ FOO_BUILD_VERSION }}
          TARGET_ARCH:  {{ FOO_TARGET_ARCH }}
    depends_on:
      - {{ RUST }}
    image: {{ FOO_IMAGE }}
    container_name: {{ FOO }}
    networks:
      - {{ FOO_BRIDGE }}
    ports:
      - "{{ FOO_PUBLISH }}"
    command: /bin/sh -c 'echo "OK"'
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
    restart: always
{%- set e = [] -%}
{% if FOO_ENVS -%}
{% for item in FOO_ENVS.split(' ') -%}
{% do e.append("{}={}".format(item, env[item])) -%}
{% endfor -%}
{% endif -%}
{% if e %}
    environment:
      - {{ e|join('\n      - ') }}
{% endif %}
  {{ BAR }}:
    build:
      context: {{ BAR_CTX }}
      dockerfile: {{ BAR_DOCKERFILE }}
      args:
          APP: {{ BAR }}
          BUILDER:  {{ BAR_BUILDER }}
          BASE_IMAGE:  {{ BAR_BASE_IMAGE }}
          BUILD_PROFILE: {{ BAR_BUILD_PROFILE }}
          BUILD_VERSION: {{ BAR_BUILD_VERSION }}
          TARGET_ARCH:  {{ BAR_TARGET_ARCH }}
    depends_on:
      - {{ RUST }}
    image: {{ BAR_IMAGE }}
    container_name: {{ BAR }}
    networks:
      - {{ BAR_BRIDGE }}
    command: /bin/sh -c 'echo "OK"'
    ports:
      - "{{ BAR_PUBLISH }}"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
    restart: always
{%- set e = [] -%}
{% if BAR_ENVS -%}
{% for item in BAR_ENVS.split(' ') -%}
{% do e.append("{}={}".format(item, env[item])) -%}
{% endfor -%}
{% endif -%}
{% if e %}
    environment:
      - {{ e|join('\n      - ') }}
{% endif %}
networks:
  {{ BRIDGE }}:
    name: {{ BRIDGE }}
    driver: {{ DRIVER }}
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: {{ NETWORK }}
  
volumes:
  postgres:
